### ISSUE TITLE
report should be comparable between test runs

### ISSUE THREAD

**Issue by lahabana** [Kong/mesh-perf#49]
So the reports should be an artifact in a good format that contains parameters (number of services, number of pods, version...) and a set of aggregated metrics (ok to start with just duration).

We should then be able to retrieve all the runs for a period of time and then plot them to compare.

**Comment by lahabana** [comment]
We could easily push an artifact with something like: `{"runId": "...", params: {"version": "..", "number_services": ...."}, [{"testName": "fewew", stats: {"duration": "fff", ....}}, ...]}`

Then we have a make target that pulls all these artifacts and generate a set of graph locally to compare these.

**Comment by lobkovilya** [comment]
After each run, we can push a log line to the datadog, so we can observe performance trends as Kong Mesh is getting updated
